name: Deploy Lambda Function

on:
  push:
    branches:
      - uat

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 1: Retrieve the list of changed files in the push
    - name: Get modified files
      id: get_modified_files
      run: |
        if git rev-parse --verify HEAD^ >/dev/null 2>&1; then
          # There is a previous commit, compare with HEAD^
          files=$(git diff --name-only HEAD^ HEAD)
        else
          # No previous commit, list all files in the current commit
          files=$(git ls-files)
        fi

        # Join file names into a single space-separated string and store in GITHUB_ENV
        files_joined=$(echo "$files" | tr '\n' ' ')
        echo "MODIFIED_FILES=$files_joined" >> $GITHUB_ENV

    # Step 2: Dynamically identify the Lambda function directory based on the changed files
    - name: Identify Lambda function directory
      id: identify_lambda_function
      run: |
        for file in $MODIFIED_FILES; do
          if [[ $file == */lambda_function.py ]]; then
            function_name=$(dirname $file)
            echo "FUNCTION_NAME=$function_name" >> $GITHUB_ENV
          fi
        done

    # Step 3: Print the Lambda function directory
    - name: Print function name
      run: |
        echo "Lambda Function Directory: $FUNCTION_NAME"

    # Step 4: Zip Lambda function from the dynamic folder
    - name: Zip Lambda Function
      run: |
        zip -j my_lambda_function.zip "$FUNCTION_NAME/lambda_function.py"

    # Step 5: Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1  # Change to your region

    # Step 6: Deploy the Lambda function
    - name: Deploy Lambda Function
      run: |
        aws lambda update-function-code --function-name "$FUNCTION_NAME" --zip-file fileb://my_lambda_function.zip

    # Step 7: Update Lambda environment variables
    - name: Update Lambda function environment variables
      run: aws lambda update-function-configuration --function-name "$FUNCTION_NAME" --environment "Variables={ENV=$ENV}"

    # Step 8: Publish new Lambda version
    - name: Publish New Version
      id: publish_version
      run: |
        VERSION=$(aws lambda publish-version --function-name "$FUNCTION_NAME" --query 'Version' --output text)
        echo "::set-output name=VERSION::$VERSION"

    # Step 9: Create or update alias for the Lambda function
    - name: Create Alias
      run: |
        aws lambda update-alias --function-name "$FUNCTION_NAME" --name "$ENV" --function-version ${{ steps.publish_version.outputs.VERSION }} || \
        aws lambda create-alias --function-name "$FUNCTION_NAME" --name "$ENV" --function-version ${{ steps.publish_version.outputs.VERSION }}

    # Optional: Reset environment variables back to dev (if needed)
    - name: Update Lambda function environment variables back to dev
      run: aws lambda update-function-configuration --function-name "$FUNCTION_NAME" --environment "Variables={ENV=dev}"
