# .github/workflows/deploy.yml
name: Deploy Lambda Function

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2


    - name: Zip Lambda Function
      run: |
        zip -r my_lambda_function.zip lambda_function.py

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1  # Change to your region

    - name: Deploy Lambda Function
      run: |
        aws lambda update-function-code --function-name test_hello_world --zip-file fileb://my_lambda_function.zip
